const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const sourceFiles = [
    "scripts/modules/startup-sequence.js",
    "scripts/modules/station-data.js",
    "scripts/modules/journals.js",
    "scripts/modules/fleet-journals.js",
    "scripts/modules/warnings.js",
    "scripts/modules/nav-routing.js",
    "scripts/modules/map-ui.js",
    "scripts/modules/state-sync.js",
    "scripts/modules/navdata.js",
    "scripts/modules/planet-intel.js",
    "scripts/modules/mission-control.js",
    "scripts/modules/clearance.js",
    "scripts/imperial-star-log.js"
];

const output = [
    "/* Generated by scripts/build-module.js. Do not edit directly. */",
    ...sourceFiles.map((file) => fs.readFileSync(path.join(root, file), "utf8").trim())
].join("\n\n") + "\n";

fs.writeFileSync(path.join(root, "scripts/galactic-operations-console.js"), output);
